export const products = [
  {
    slug: "uber-greens",
    name: "Uber Greens",
    category: "Greens",
    badge: "BESTSELLER",
    badgeColor: "bg-[#c5e47a] text-[#1a4a0a]",
    cardBg: "bg-[#eaf5e0]",
    heroBg: "#3daa57",
    word: "UBER GREENS",
    emoji: "🥒",
    price: 299,
    rating: 4.9,
    reviews: 128,
    desc: "Cucumber · Celery · Grapefruit · Chard · Lemon",
    ingredients: [
      { icon: "🥒", name: "Cucumber" },
      { icon: "🌿", name: "Celery" },
      { icon: "🍋", name: "Lemon" },
      { icon: "🌱", name: "Chard" },
      { icon: "🍇", name: "Grapefruit" },
    ],
    benefits: [
      { icon: "⚡", text: "Boosts Energy" },
      { icon: "🧠", text: "Mental Clarity" },
      { icon: "🌿", text: "Detox & Cleanse" },
    ],
    sizes: ["500ml", "300ml", "100ml"],
  },
  {
    slug: "citrus-zest",
    name: "Citrus Zest",
    category: "Immunity",
    badge: "IMMUNITY",
    badgeColor: "bg-[#ffd980] text-[#7a4a00]",
    cardBg: "bg-[#fff8e8]",
    heroBg: "#f5a020",
    word: "CITRUS ZEST",
    emoji: "🍍",
    price: 329,
    rating: 4.8,
    reviews: 94,
    desc: "Pineapple · Citrus · Vitamin C · Ginger · Acerola",
    ingredients: [
      { icon: "🍍", name: "Pineapple" },
      { icon: "🍊", name: "Citrus" },
      { icon: "💊", name: "Vitamin C" },
      { icon: "🫚", name: "Ginger" },
      { icon: "🍒", name: "Acerola" },
    ],
    benefits: [
      { icon: "🛡️", text: "Immunity Boost" },
      { icon: "💊", text: "Vitamin Rich" },
      { icon: "🔥", text: "Anti-Inflammatory" },
    ],
    sizes: ["500ml", "300ml", "100ml"],
  },
  {
    slug: "berry-boost",
    name: "Berry Boost",
    category: "Gut Health",
    badge: "GUT HEALTH",
    badgeColor: "bg-[#f9b8d0] text-[#7a1a3a]",
    cardBg: "bg-[#fdeef4]",
    heroBg: "#d9255e",
    word: "BERRY BOOST",
    emoji: "🍓",
    price: 349,
    rating: 4.7,
    reviews: 76,
    desc: "Berry · Lemon · Probiotics · Prebiotic Fiber · Cherry",
    ingredients: [
      { icon: "🍓", name: "Berry" },
      { icon: "🍋", name: "Lemon" },
      { icon: "🦠", name: "Probiotics" },
      { icon: "🌾", name: "Prebiotic Fiber" },
      { icon: "🍒", name: "Cherry" },
    ],
    benefits: [
      { icon: "🫀", text: "Gut Health" },
      { icon: "🦠", text: "Probiotics" },
      { icon: "✨", text: "Skin Glow" },
    ],
    sizes: ["500ml", "300ml", "100ml"],
  },
];

export const filters = ["All", "Greens", "Immunity", "Gut Health", "Energy"];